# -*- coding: utf-8 -*-
"""Decision tree(gini index)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwXCawfjfCqi3FqP2h4m2HmCeMWR3Krw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

"""# New Section"""

df=pd.read_csv("/content/cardio disease.csv")
print(df)

df.max()

x= df.iloc[:,[1,8]]
y= df.iloc[:,3]
print(x)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=0)
print(x_train)

from sklearn.preprocessing import StandardScaler
st_x=StandardScaler()
x_train=st_x.fit_transform(x_train)
x_test=st_x.transform(x_test)
print(x_test)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='gini',random_state=0)
classifier.fit(x_train,y_train )
y_pred=classifier.predict(x_test)
print(y_pred)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

import matplotlib.pyplot as plt
import numpy as np
y_pred=classifier.predict(x_test)
plt.plot(y_pred)
plt.show

cm=confusion_matrix(y_test,y_pred)
plt.plot(cm)
plt.show

from sklearn.tree import export_graphviz
import graphviz
graphviz.Source(export_graphviz(classifier,feature_names=x.columns,filled=True))